-- UTWORZENIE BAZY
CREATE DATABASE librex2;

-- SŁOWNIKI I TABELKI POMOCNICZE

CREATE TABLE permissions_dict (
    permission_id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role             VARCHAR(50) NOT NULL
);

CREATE TABLE countries_dict (
    country_id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    country_name     VARCHAR(100) NOT NULL
);

CREATE TABLE genre_dict (
    genre_id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name             VARCHAR(100) NOT NULL
);

CREATE TABLE languages_dict (
    language_id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    language         VARCHAR(50) NOT NULL
);

CREATE TABLE categories_dict (
    category_id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name             VARCHAR(100) NOT NULL
);


-- USERS, AUTHORS, PUBLISHERS

CREATE TABLE users (
    user_id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    permission_id    INTEGER NOT NULL,
    country_id       INTEGER,
    firstname        VARCHAR(50) NOT NULL,
    surname          VARCHAR(50) NOT NULL,
    address          VARCHAR(100),
    birthdate        DATE,
    phone            VARCHAR(30),
    email            VARCHAR(100) NOT NULL UNIQUE,
    username         VARCHAR(50) NOT NULL UNIQUE,
    password         VARCHAR(255) NOT NULL,
    is_blacklisted   BOOLEAN NOT NULL DEFAULT FALSE,

    CONSTRAINT fk_users_permission
        FOREIGN KEY (permission_id) REFERENCES permissions_dict(permission_id),

    CONSTRAINT fk_users_country
        FOREIGN KEY (country_id) REFERENCES countries_dict(country_id)
);

CREATE TABLE authors (
    author_id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    firstname        VARCHAR(50) NOT NULL,
    surname          VARCHAR(50) NOT NULL,
    nickname         VARCHAR(50),
    nationality      VARCHAR(100),
    birthdate        DATE,
    deathdate        DATE,
    genre_id         INTEGER,

    CONSTRAINT fk_authors_genre
        FOREIGN KEY (genre_id) REFERENCES genre_dict(genre_id)
);

CREATE TABLE publishers (
    publisher_id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name             VARCHAR(100) NOT NULL,
    address          VARCHAR(100),
    country_id       INTEGER,
    email            VARCHAR(100) UNIQUE,
    webpage          VARCHAR(100),
    foundation_date  DATE,

    CONSTRAINT fk_publishers_country
        FOREIGN KEY (country_id) REFERENCES countries_dict(country_id)
);


-- BOOK TITLE / EDITION / COPY

CREATE TABLE book_title (
    title_id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title            VARCHAR(200) NOT NULL,
    author_id        INTEGER NOT NULL,
    description      TEXT,

    CONSTRAINT fk_book_title_author
        FOREIGN KEY (author_id) REFERENCES authors(author_id)
);

CREATE TABLE book_edition (
    edition_id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title_id         INTEGER NOT NULL,
    publisher_id     INTEGER,
    isbn             VARCHAR(20) UNIQUE,
    language_id      INTEGER,
    pages            INTEGER,
    publish_year     INTEGER,
    is_hard_cover    BOOLEAN,
    value            NUMERIC(10,2),
    notes            TEXT,

    CONSTRAINT fk_edition_title
        FOREIGN KEY (title_id) REFERENCES book_title(title_id) ON DELETE CASCADE,

    CONSTRAINT fk_edition_publisher
        FOREIGN KEY (publisher_id) REFERENCES publishers(publisher_id),

    CONSTRAINT fk_edition_language
        FOREIGN KEY (language_id) REFERENCES languages_dict(language_id)
);

CREATE TABLE book_copy (
    copy_id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inventory_num    VARCHAR(50) NOT NULL UNIQUE,
    edition_id       INTEGER NOT NULL,
    condition        VARCHAR(100),
    defects          TEXT,
    is_available     BOOLEAN NOT NULL DEFAULT TRUE,

    CONSTRAINT fk_copy_edition
        FOREIGN KEY (edition_id) REFERENCES book_edition(edition_id) ON DELETE CASCADE
);


-- KATEGORIE (M:N)

CREATE TABLE book_categories (
    category_id      INTEGER NOT NULL,
    title_id         INTEGER NOT NULL,

    CONSTRAINT pk_book_categories
        PRIMARY KEY (title_id, category_id),

    CONSTRAINT fk_book_categories_category
        FOREIGN KEY (category_id) REFERENCES categories_dict(category_id) ON DELETE CASCADE,

    CONSTRAINT fk_book_categories_title
        FOREIGN KEY (title_id) REFERENCES book_title(title_id) ON DELETE CASCADE
);


-- REZERWACJE, LISTA OCZEKUJĄCYCH, KARY

CREATE TABLE reservations (
    reservation_id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id              INTEGER NOT NULL,
    create_date          TIMESTAMP NOT NULL,
    return_date          DATE,
    expected_return_date DATE NOT NULL,
    is_damaged           BOOLEAN NOT NULL DEFAULT FALSE,
    damage_details       VARCHAR(500),
    copy_id              INTEGER NOT NULL,

    CONSTRAINT fk_res_user
        FOREIGN KEY (user_id) REFERENCES users(user_id),

    CONSTRAINT fk_res_copy
        FOREIGN KEY (copy_id) REFERENCES book_copy(copy_id)
);

CREATE TABLE waitlist (
    waitlist_id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          INTEGER NOT NULL,
    title_id         INTEGER NOT NULL,
    is_active        BOOLEAN NOT NULL DEFAULT TRUE,
    create_date      TIMESTAMP NOT NULL,
    position         INTEGER,

    CONSTRAINT fk_waitlist_user
        FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,

    CONSTRAINT fk_waitlist_title
        FOREIGN KEY (title_id) REFERENCES book_title(title_id) ON DELETE CASCADE,

    CONSTRAINT uq_waitlist_user_title
        UNIQUE (user_id, title_id),

    CONSTRAINT uq_waitlist_title_position
        UNIQUE (title_id, position)
);

CREATE TABLE penalties (
    penalty_id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reservation_id   INTEGER NOT NULL UNIQUE,
    amount           NUMERIC(10,2) NOT NULL,
    days_late        INTEGER NOT NULL,
    created_at       TIMESTAMP NOT NULL,
    is_paid          BOOLEAN NOT NULL DEFAULT FALSE,
    paid_at          TIMESTAMP,

    CONSTRAINT fk_penalty_reservation
        FOREIGN KEY (reservation_id) REFERENCES reservations(reservation_id) ON DELETE CASCADE
);
